### ISSUE TITLE
Add support for Minecraft 1.18.2

### ISSUE THREAD

**Issue by Poopooracoocoo** [grondag/clear-skies#8]

**Comment by triphora** [comment]
This is only a matter of bumping the MC version in the fabric.mod.json. The mod works fine on 1.18.2 via dependency overrides. Add a file in your `config` folder with the name `fabric_loader_dependencies.json` and the following contents:
```json
{
  "version": 1,
  "overrides": {
    "clear-skies": {
      "-depends": {
        "minecraft": ""
      }
    }
  }
}

```

**Comment by JustFoxx** [comment]
We need it but for curseforge

**Comment by Snowy893** [comment]
> This is only a matter of bumping the MC version in the fabric.mod.json. The mod works fine on 1.18.2 via dependency overrides. Add a file in your `config` folder with the name `fabric_loader_dependencies.json` and the following contents:
> 
> ```json
> {
>   "version": 1,
>   "overrides": {
>     "clear-skies": {
>       "-depends": {
>         "minecraft": ""
>       }
>     }
>   }
> }
> ```

this crashed my game when i added this in my config folder?

nvm, my game crashed without clear skies and this, its probably an issue with my modpack or something

**Comment by grondag** [comment]
1.18.2 version now available
